### ISSUE TITLE
validate_presence_of is missing expect clause

### ISSUE THREAD

**Issue by kalabiyau** [NadjaW/TeamDashboard#2]
Those tests should be rewritten to actually test things

https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L69
https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L55
https://github.com/NadjaW/TeamDashboard/blob/master/spec/models/user_spec.rb#L41

Idea:

we can use http://www.rubydoc.info/github/thoughtbot/shoulda-matchers/master/Shoulda/Matchers/ActiveModel#validate_presence_of-instance_method

for doing that. Please ping me if you need any help

**Comment by NadjaW** [comment]
Tests rewritten

**Comment by kalabiyau** [comment]
@NadjaW please push your changes to github, so I can check them

**Comment by NadjaW** [comment]
pushed :)
